### PR TITLE
Odim lenovo

### PR DESCRIPTION
**Pull request by sunithasomanna**
Lenovo plugin deployment instructions

### CODE REVIEW

**Review by amar-shalgar — CHANGES_REQUESTED** [review]
Should merge the lenovo details in PluginLenovo_Issue-549 branch

**Comment by sunithasomanna** [comment]
> Should merge the lenovo details in PluginLenovo_Issue-549 branch

Done! Changed the base branch

**Review by amar-shalgar — APPROVED** [review]
Lenovo deployment details LGTM

**Comment by sunithasomanna** [comment]
Closing this PR because the upstream feature branch of Lenovo plugin readme reflects the required content (latest content).

**Pull request closed without merging**
